services:
  whisper-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./audio:/app/audio # ローカルの audio ディレクトリをコンテナ内にマウント
    environment:
      - AUDIO_DIR=/app/audio # 音声ファイルのディレクトリパス
    depends_on:
      - whisper
    networks:
      - whisper-net

  whisper:
    image: ghcr.io/jim60105/whisperx:no_model
    volumes:
      - ./audio:/app/audio # whisper コンテナでも音声ファイルにアクセスできるようにする
      - whisper_cache:/.cache # align models cache
    networks:
      - whisper-net

networks:
  whisper-net:
    driver: bridge

volumes:
  whisper_cache:
